### ISSUE TITLE
Route limits cause updates to fail

### ISSUE THREAD

**Issue by LewS** [base2Services/cfn-vpn#10]
ClientError: An error occurred (ClientVpnRouteLimitExceeded) when calling the CreateClientVpnRoute operation: Limit exceeded

We could create an ssm param to hold the current limit and invoke a limit increase if the error contains ClientVpnRouteLimitExceeded

**Comment by Guslington** [comment]
shipped in version 1.4.0 https://github.com/base2Services/cfn-vpn/releases/tag/1.4.0
