### ISSUE TITLE
[Feature Request] A CodeCommit repository, build and pipeline for managing VPN config

### ISSUE THREAD

**Issue by mitchclarkebase2** [base2Services/cfn-vpn#18]
After the amazing success of using CodeCommit repos with cfn-guardian I think doing something similar for cfn-vpn would be really useful. At the moment we are basically doing cfn-monitor but for VPN management. Having to look through docs, command history and discussions about how to make things work, it seems that things could be simpler, and easier.

It might feel like overkill since we don't usually change Client VPN config very often, and the changes are minimal, but being able to just log into the appropriate account, open the repo to either view or modify the config would make life a lot easier. You could have a list of users, routes, groups etc that CodeBuild would be able to interpret into cfn-vpn commands or something completely different. 

One example is I just added a new route to a VPN with groups associated, however I had to dig in Slack conversations to find out that the reason it didn't work properly is because of a bug we found last year which means you have to run the command twice for it to work. If we had a config repo you would add the new route, then CodeBuild would see that and know to run the command twice or do something more intelligent to get the change made. 

This could be an optional bearse feature in the end, as you could deploy the repo and pipeline etc, then enter all of the necessary details in the config i.e. subnet to associate with, routes to make, users etc.

It just feels like the current method is behind the times, and we should move this great tool into a far more sophisticated management system.

**Comment by Guslington** [comment]
closing as tracking this feature on a internal board
